@baseUrl=https://aimsinterface-production.up.railway.app/wsdl
###
GET {{baseUrl}}?wsdl HTTP/1.1

###
POST {{baseUrl}} HTTP/1.1
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope>
   <soap:Body>
      <urn:getSubjects />
   </soap:Body>
</soap:Envelope>
